version: 2 

jobs: 
  build: 
    working_directory: ~/api-template-laravel 

    docker: 
      - image: circleci/php:7.3.4-fpm-stretch
        environment:
          APP_ENV: circleci

      - image: circleci/postgres:10.7-alpine
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres

    steps: 
      - checkout 
      - run:
          name: apt update/install
          command: |
            sudo apt-get update
            sudo apt-get install -y libpq-dev

      - run: sudo apt install -y postgresql-client || true

      - run: sudo docker-php-ext-install bcmath pdo_pgsql
      - run: sudo composer self-update
      - restore_cache: 
          keys:
            - composer-v1-{{ checksum "laravel/composer.lock" }}
            - composer-v1-
      - run:
          name: composer install
          command: |
            cd laravel
            composer install -n --prefer-dist
      - save_cache: 
          key: composer-v1-{{ checksum "laravel/composer.lock" }}
          paths:
            - laravel/vendor

      - run:
          name: cp .env
          command: |
            cd laravel
            cp .env.testing .env

      - run:
          name: init db
          command: |
            psql -h localhost -p 5432 -U postgres -f tools/sql/01_create_db_dev.sql
            cd laravel
            php artisan migrate

      - run:
          name: phpunit
          command: |
            cd laravel
            phpdbg -qrr ./vendor/bin/phpunit -d memory_limit=512M

      - store_artifacts:
          path: ./phpunit/html
          destination: coverage

      - store_test_results:
          path: ./phpunit
