query {
    users {
        id
        email
        name
        articles {
            id
            subject
            content
        }
        comments {
            id
            content
        }
    }
}
